/* empty css                      */import{S as d,A as p,P as h}from"./assets/vendor-Bvc6Cv_u.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const m=1440;let n=null,a=null,u=null,c=null;const f={delay:3e3,disableOnInteraction:!1,pauseOnMouseEnter:!0};function w(s){var l;if(!((l=s.pagination)!=null&&l.bullets))return;const r=Array.from(s.pagination.bullets),i=s.realIndex;r.forEach((e,t)=>{if(e.classList.remove("features-bullet-active","features-bullet-next","features-bullet-small"),t===i){e.classList.add("features-bullet-active");return}const o=(i+1)%r.length;t===o?e.classList.add("features-bullet-next"):e.classList.add("features-bullet-small")})}function y(){document.querySelector(".how-swiper")&&(n||(n=new d(".how-swiper",{modules:[p],slidesPerView:1.4,spaceBetween:24,loop:!0,speed:700,autoplay:f})),!a&&document.querySelector(".features-swiper")&&(a=new d(".features-swiper",{modules:[p,h],slidesPerView:1,spaceBetween:16,loop:!0,speed:700,autoplay:f,pagination:{el:".features-pagination",clickable:!0,bulletClass:"features-pagination-bullet",bulletActiveClass:"features-pagination-bullet-current"},on:{init(s){w(s)},slideChange(s){w(s)},paginationUpdate(s){w(s)}}})),!u&&document.querySelector(".gallery-swiper")&&(u=new d(".gallery-swiper",{modules:[p],slidesPerView:1.5,spaceBetween:16,loop:!0,speed:700,autoplay:f})),!c&&document.querySelector(".reviews-swiper")&&(c=new d(".reviews-swiper",{modules:[p],slidesPerView:1.45,spaceBetween:8,loop:!0,speed:700,autoplay:f})))}function v(){n&&(n.destroy(!0,!0),n=null),a&&(a.destroy(!0,!0),a=null),u&&(u.destroy(!0,!0),u=null),c&&(c.destroy(!0,!0),c=null)}function g(){window.innerWidth<m?y():v()}g();window.addEventListener("resize",g);document.querySelectorAll(".faq-acc-el-trigger").forEach(s=>{s.addEventListener("click",()=>{const r=s.closest(".faq-acc-el"),i=r.querySelector(".faq-acc-el-descr-frame"),l=s.querySelector("svg"),e=r.classList.contains("open"),t=`
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M4.16602 10H15.834M10 4.16602V15.834" stroke="#9D85FF" stroke-width="2" stroke-linecap="round" />
</svg>`,o=`
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
  <g clip-path="url(#clip0_19_178)">
    <path d="M4.16675 10H15.8334" stroke="#9D85FF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  </g>
  <defs>
    <clipPath id="clip0_19_178">
      <rect width="20" height="20" fill="white" />
    </clipPath>
  </defs>
</svg>`;e?(r.classList.remove("open"),i.style.maxHeight="0",l.outerHTML=t):(r.classList.add("open"),i.style.maxHeight=i.scrollHeight+"px",l.outerHTML=o)})});
//# sourceMappingURL=index.js.map
